### ISSUE TITLE
TODO Review

### ISSUE THREAD

**Issue by severin-lemaignan** [chili-epfl/paper-anthropomorphism-eyetracking#1]
## Literature/theoretical background
- [ ] provide a theoretical rationale for the “shallow vs. deep cognitive context” notion (Issue #2)
- [ ] The term “cognitive“ context is uncommon in psychology and would need references.
- [ ] Please also read more closely into other works on the cognitive processes underlying visual attention and gazing behavior (e.g. Deubel, Irwin & Schneider, 2004). Here, too, the audience needs more background as to why the authors believe that gaze behavior supposedly reflects a positive attitude towards a robot (i.e., in terms of higher anthropomorphisation). This is theoretically unclear as well as from the viewpoint of operationalization
- [ ] notion of a “proxy.” The sensitivity of head fixations to the “context” manipulation does not establish a proxy role of eye movements; it establishes only a causal impact of the manipulation on eye movements. [...] The idea that it is a more subtle measure than self-reports may be preferable, but supportive data or arguments need to be provided
- [ ] Maybe literature on scene perception from cognitive psychology could be informative as well, as tracking gaze data based on a video could introduce problems.
- [ ] Overall, the literature review as is gives the impression that the authors will have to rework the theoretical background and have to build the experimental hypothesis on this. However, I am missing a lot of literature here and the overview provided falls too short. There are key papers on anthropomorphism missing (e.g. by Eyssel and colleagues who were first to use human-related traits in HRI, see Ro-Man 2010 paper; or by Kuchenbrandt et al., who have relied on reaction-time based measures of anthropomorphism).
- [ ] the introduction could use a stronger argument for the need for a new measure
- [ ] more needs to be said about generic anthropomorphism vs. anthropomorphizing a particular robot: if the authors want to claim that their technique is measuring generic anthropomorphism, the theoretical framing of the paper needs to make a case that deep vs. shallow context should affect this generic anthropomorphism. Most arguments seem more aligned with the view that context is going to affect the degree to which a participant anthropomorphizes a specific robot.

Other literatture to be considered:
- [ ] Deubel, H. & Schneider, W.X. (2004). Attentional selection in sequential manual movements, movements around an obstacle and in grasping. In: G. W. Humphreys and M.J. Riddoch (Eds), Attention in Action, Hove: Psychology Press.
- [ ] Eyssel, F., Hegel, F., Horstmann, G. & Wagner, C. (2010). Anthropomorphic inferences from emotional nonverbal cues: A case study. Proceedings of the 19 th IEEE International Symposium in Robot and Human Interactive Communication (RO-MAN 2010), 681-686. DOI: 10.1109/ROMAN.2010.5598687
- [ ] Eyssel, F., Kuchenbrandt, D. & Bobinger, S. (2011). Effects of anticipated human-robot interaction and predictability of robot behavior on perceptions of anthropomorphism.Proceedings of the 6 th ACM/IEEE Conference on Human-Robot Interaction (HRI 2011), 61-67.
- [ ] Horstmann, G., & Herwig, A. (2015). Surprise attracts the eyes and binds the gaze. Psychonomic Bulletin & Review, 22, 743-749 or
- [ ] Kuchenbrandt, D., Häring, M., Eichberg, J. & Eyssel, F. (2012). Keep an eye on the task! How gender typicality of tasks influence human-robot interactions. Lecture Notes in Computer Science, 7621, 448-457. Berlin/Heidelberg: Springer.
- [ ] Kuchenbrandt, D., Eyssel, F., Bobinger, S. & Neufeld, M. (2013). When a robot’s group membership matters: Anthropomorphization of robots as a function of social categorization. International Journal of Social Robotics, 5, 409-417. DOI: 10.1007/s12369-013-0197-8.
## Design
- [ ] The aforementioned works and the present references should be described more in detail. This will make it easier to understand the choice of independent variables in the 2x2. For instance, it is unclear to me, why the context was manipulated after all (wouldn’t robot vs. human target be enough to begin with?). Similarly, I am not sure if a human would be an optimal control condition – the choice of targets (NAO vs. human) needs further explanation. It is hard to compare both videos given the different sizes of robotic vs. human target). Why was a male target chosen and not both male and female?
- [x] Figure 1 appears tautological, frame hypotheses in terms of mediation, moderation, but this presents literally “circular“ arguments. The „interaction“ described here is neither mirrored in Hypotheses 1-4 nor in the actual analyses [REMOVED FIGURE]. These, at the same time should be reworked in terms of shorter, clearly testable statements.
- [ ] Maybe the statement in the shallow cognitive context should have read „“Point at the SOURCE of noise“ - I still do not understand, however, if this would indeed be interpreted as a machine-like situation (see 2.0,p. 4). As said, this must be established by a pretest.
- [ ] Table 1 somewhat confusing. While the design is described by the authors as being 2 (robot/human) x 2 (deep/shallow), there are also 2 different tasks (e.g. picking/pointing) and I can't determine from the text what has happened with this manipulation. Did a given participant saw human+pick, robot+pick, human+point and robot+point videos if they were in the shallow condition or did they see "pick" once with a human or robot and "point" with the other agent?
- [ ] Why should legs and torso be chosen as AOI – I believe, logically, head and hands could be compared.
- [ ] I wonder why the authors did not measure mind attribution to a robot (see Eyssel & Kuchenbrandt, 2012; see also Gray, Gray & Wegner, 2007) – particularly when the iVs address deep vs. shallow processing.
- [ ] I would also like to see greater justification for the assumption that greater anthropomorphism = more similar gaze patterns to the human actor is required. This is because gaze patterns toward human actors also vary, e.g. they can be affected by the person's gender. If by some chance the participants viewed the robot as female but the actor as male, then we might not expect that the gaze patterns to be highly correlated even when there is high anthropomorphism of the robot.
## Methodology
- [ ] The manipulation check used does not seem appropriate and it is unclear when exactly and in respect to which video (i.e. how often) the manipulation check question was asked - twice?
- [ ] Once the meaning of “context” is clarified, the manipulation check must address this clarified meaning (e.g., command implication).
- [x] The manipulation check asks about a robot vs. human kind of task. At the same time, this is a within-subjects factor – this needs further explanation and does not seem to make sense (e.g. could be biased by the type of task done last (i.e. task order). By the way, since order was counterbalanced, was there an effect?
- [ ] Provide appropriate, clear, and well-argued information about methodology (and add convincing “post”tests [4pretests that are run after the experiment] for the major “context” manipulation), including all instructions and (translated?) formulations of used measures. An Appendix would be appropriate for at least the central material. If the manuscript becomes too long, use github. But do not relegate details of statistical analysis to such a repository.
- [ ] revision will almost certainly require another study in which you include an adequate control condition (e.g., mere observation of human vs. robot and thereby baseline of gaze patterns)
- [ ] Regarding measurement – what about first fixations, saccades and other indicators besides dwell time? These should be reported.
- [ ] A pretest should have assured that the independent variables operationalize the constructs of interest adequately (again, not sure why level of cognitive context should lead participants to perceive a situation as more robot- vs. humanlike (p. 5); further, it appears unclear why it is needed in this experiment, after all)
- [ ] Was the time used for free play recorded? Why was it unlimited and not fixed – whereas on the other hand, time to complete the self-report at baseline was fixed to 10 mins?
- [ ] I am surprised to read that all participants seemed trackable with the eyetracker. Often, particularly women are hard to track because of make-up. If the authors had an initially larger sample, this needs to be conveyed. Also, if that were the case, were other participants omitted from analyses and why?
- [ ] Was the voice sample of the speaker pretested, was it male vs. female? Details are
  missing on p. 5
## Results
- [ ] reported eye tracking results are far too cursory. In addition, you need to address that head fixations to the robot could increase because people are curious whether the robot really has the implied capacities, not because they assume it has them. Can you rule out this alternative interpretation?
- [ ] Whatever dependent variable you use to capture gaze patterns (the reported difference score is problematic; see my in-text comment) must be the same for H2 and H3.
- [ ] Clarify the differential measurement and impact of “context” on specific vs. generalized anthropomorphism.
- [ ] you should increase statistical power in this replication, because your main results are barely significant
- [ ] The measures on familiarity with robots have to be presented in the Materials section, not just in the participants section
- [x] No additional reference to participants only taking part once (p. 6, 3.1) should be
  needed. This should be standard. **Fixed via b590aeb**
- [x] What was actually piloted with 10 participants? And what was the outcome? Otherwise: Why mention it after all on p. 6? **Fixed via 5857a56** (removed mention of the pilot)
- [ ] We need exemplar items in section 2.3 (p.5) - mere reference to a link is not sufficient
- [ ] I would recommend to rephrase „biases“ in the result section. We are checking for main effects of participant gender, age, etc. not for distortions.
- [ ] How were the anthropomorphism indices computed? I believe Ruijten uses the Rasch-scale method. The authors, however do not provide any details on mean computation, standard deviations, internal consistencies
- [ ] Overall, the results section is lacking important information: Regarding analyses, the authors have to clearly describe 
  - [ ] what analyses were conducted and why. 
  - [ ] Further, how these statistics would test the outlined hypotheses. Key information is missing here and analyses seem not to be sound (e.g., means and standard deviations are missing, F-values are reported when the authors talk about a correlation (section 4.2) and Figures 6 and 7 are just presented, not explained further; Section 4.5 mentions an „ANOVA against the chance of ...“ --- this is not adequate reporting of statistical analyses and the respective findings.
  - [ ] What about repeated measures ANOVAs in light of the within-subjects factor –what about the analyses on effects of gender, age, ... Why correlation analyses, what about running multiple regression analyses? These analyses might be more appropriate in testing the hypotheses.
- [ ] Most importantly, in order to validate a eyetracking as a proxy for anthropomorphisation, indicators of visual attention could be correlated, indeed, with explicit self-reports. Otherwise, it is hard to assume that the assumptions of the authors uphold. There is vast literature on first fixations on a target’s head, so this could and should be analyzed in the data as well.
- [ ] I found the scales and their usage to be confusing. The authors state on p. 5 that, "[delta score] in particular, reflects the impact of the video stimuli on the anthropomorphic perception that they have of robots in general: the Godspeed questions used in the questionnaires are not specific to the Nao robot used in this particular experiment, and indeed assess how humans perceive robots in a broad sense." But I don't understand why this would be the case unless they had changed the general instructions used in the actual Godspeed surveys, which ask about "the robot" not "robots in general." More details on the survey materials, including more examples of the actual wording, are needed here.
- [ ] with respect to the data analysis, I can't determine what has happened to the task level data. If the gaze data was combined across tasks, then some preliminary stats showing that it islegitimate to do that are needed. Otherwise I would expect to see separate analyses for each of these tasks.
- [ ] Why mention the Big 5 but then state that the measures aren't used in this study? Perhaps it would be best to combine this data with another paper that does look at personality, since this paper is fairly slight on contribution.
## Discussion
- [ ] Clearly, the experiment doesn’t feature actual HRI and this needs critical discussion.
- [ ] I would recommend to start with a broader statement regarding the research question, the theoretical and empirical gain, the benefit of eyetracking for HRI, then present supporting evidence and provide ideas for follow-up experiments that rule out shortcomings of the current experiments (confounds like target size, task type, gender of human target,..) and its design (e.g., replicating it with other platforms or comparing humans vs. androids vs. machinelike robots, if needed (but again: what’s the theoretical rationale here? Elicited agent knowledge according to Epley?) How to rule out salience effects, visual novelty, etc? This needs to be discussed critically. If these issues could be provided in a more coherent, convincing way, it would be great.
- [ ] In my view, the paper ends very abruptly with a statement on measurement tools – this is not what one would expect in terms of an outlook and a vision for future research on eyetracking within HRI.
- [ ] Figure 7 would be more compelling if the human data was also included to demonstrate that the manipulation had no effect on perception of humans. The fact that it is robot only should be stated in the figure caption so that it's obvious.
## Style/Formatting
- [x] Follow the journal guidelines (APA format, etc.) in detail. Guidelines are available at http://www.humanrobotinteraction.org/journal/index.php/HRI/about/submissions#authorGuidelines. **Fixed via 08d12ba09**
- [ ] Finally, the paper contained many errors of spelling, grammar, phrasing. Nonnative English speakers are expected to consult with a native speaker before submitting manuscripts.
- [ ] Stick to one terminology throughout the paper (e.g. cognitive vs. socio-cognitive
  context, p. 4).
- [x] Please avoid redundancy (e.g. p. 7, number of participants (please do not speak of “subjects“, following APA rules) **Fixed via df95f1781**
- [x] The procedure section needs revision: E.g. reimbursement is mentioned along with measurement Time 2 – but no reference to any debriefing is provided. Were participants not informed about the actual purpose of the study? **Fixed via 793b419**
- [x] I would not use bold statements in the discussion. The writings itself should convey the core aspects clearly enough so that additional emphases via layout should not be needed. **Fixed via d406a01**
- [x] Not sure if Fig.3 is needed if Procedure (not: course of the study) would be described in a less redundant, more clear and structured manner. **Fixed via fc30d1f**
- [x] Figure 3 is unnecessary; this is obvious from the text. **Fixed via fc30d1f**
- [ ] Figure axis text is much too small and very difficult to read even when the document is enlarged substantially.
